package com.isslng.banking.processor.drools;

import com.isslng.banking.processor.entities.TransactionInput;
import com.isslng.banking.processor.utils.TransactionEvaluatorUtils;
import java.util.Map;
import java.util.ArrayList;

global String topicLevel

rule "Notify user for customer accounts starting with 70"
	when
		$ti : TransactionInput(fieldStartsWith(transactionFields, "contraAccount", "70"))
	then
		TransactionEvaluatorUtils.setUserNotificationChannels($ti, "COMPLETED", "simple-email");
		TransactionEvaluatorUtils.setUserNotificationChannels($ti, "APPROVED", "simple-sms");
		TransactionEvaluatorUtils.setNotificationLevels($ti, "ALL", "USER");
		$ti.setNeedsApproval(true);
	end


rule "Require approval for transactions greater than 500000"
	when
		$ti : TransactionInput(fieldGreaterThan(transactionFields, "amount", 500000))
	then
		$ti.setNeedsApproval(true);
	end

rule "Require approval for customer accounts starting with 50"
	when
		$ti : TransactionInput(fieldStartsWith(transactionFields, "contraAccount", "50"))
	then
		$ti.setNeedsApproval(true);
	end

rule "Notify user and tenant for customer accounts starting with 80"
	when
		$ti : TransactionInput(fieldStartsWith(transactionFields, "contraAccount", "80"))
	then
		ArrayList $levels = new ArrayList();
		$levels.add("USER");
		$levels.add("TENANT");
		$ti.meta("COMPLETED",$levels);
	end



function boolean isPupilIdValid(String pupilId){
	if(pupilId.startsWith("PUP") && pupilId.length() == 12)
		return true;
	else
		return false;
}

function boolean isSchoolTransaction(String code){
	return code.startsWith("SCH");
}

function boolean fieldGreaterThan(Map fields, String field, int value){
	int val = (int) fields.get(field);
	return (val > value);
}
function boolean fieldStartsWith(Map fields, String field, String value){
	String val = (String) fields.get(field);
	return (val.startsWith(value));
}
